version: '3.1'
services:
  stats-server:
    build: ./stats
    image: stats-image
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring.datasource.url=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: always


  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always

  ewm-service:
    build: ./server
    image: server-image
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: always

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always