    DROP TABLE IF EXISTS users, compilations, locations, events, requests, categories,
     compilations_events, location_groups, location_groups_events;

    CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR NOT NULL,
        email VARCHAR NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY (id),
        CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

    CREATE TABLE IF NOT EXISTS locations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        lat float NOT NULL,
        lon float NOT NULL,
        CONSTRAINT pk_location PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR NOT NULL,
        CONSTRAINT pk_category PRIMARY KEY (id),
        CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
    );


    CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        annotation VARCHAR NOT NULL,
        category_id BIGINT NOT NULL,
        confirmed_requests BIGINT,
        created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        description VARCHAR NOT NULL,
        event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        initiator_id BIGINT NOT NULL,
        location_id BIGINT NOT NULL,
        is_paid BOOLEAN NOT NULL,
        participant_limit BIGINT,
        published_on TIMESTAMP WITHOUT TIME ZONE,
        is_request_moderation BOOLEAN NOT NULL,
        state VARCHAR NOT NULL,
        title VARCHAR NOT NULL,
        views BIGINT NOT NULL,
        CONSTRAINT pk_event PRIMARY KEY (id),
        FOREIGN KEY (category_id) REFERENCES categories (id),
        FOREIGN KEY (initiator_id) REFERENCES users (id),
        FOREIGN KEY (location_id) REFERENCES locations (id)
    );

    CREATE TABLE IF NOT EXISTS compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        is_pinned BOOLEAN,
        title varchar NOT NULL,
        CONSTRAINT pk_compilation PRIMARY KEY (id),
        CONSTRAINT UQ_COMPILATIONS_TITLE UNIQUE (title)
    );


    CREATE TABLE IF NOT EXISTS compilations_events (
        compilation_id BIGINT NOT NULL,
        event_id BIGINT NOT NULL,
        FOREIGN KEY (compilation_id) REFERENCES compilations (id),
        FOREIGN KEY (event_id) REFERENCES events (id)
    );

    CREATE TABLE IF NOT EXISTS requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        event_id BIGINT NOT NULL,
        requester_id BIGINT NOT NULL,
        status VARCHAR NOT NULL,
        CONSTRAINT pk_request PRIMARY KEY (id),
        FOREIGN KEY (event_id) REFERENCES events (id),
        FOREIGN KEY (requester_id) REFERENCES users (id)
    );

    CREATE TABLE IF NOT EXISTS location_groups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR NOT NULL,
        lat float NOT NULL,
        lon float NOT NULL,
        radius float NOT NULL,
        description VARCHAR,
        CONSTRAINT pk_location_groups PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS location_groups_events (
        location_group_id BIGINT NOT NULL,
        event_id BIGINT NOT NULL,
        FOREIGN KEY (location_group_id) REFERENCES location_groups (id),
        FOREIGN KEY (event_id) REFERENCES events (id)
    );